config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  resources :groups
  resources :users

  root 'static_pages#index'
  get  'static_pages/index'

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @users = User.all
  end

  # GET /groups/1/edit
  def edit
    @users = User.all
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
    if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name,:user_ids => [])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	@users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
    @groups = Group.all
  end

  def show
    @groups = Group.all
  end

  def new
    @groups = Group.all
  end

  def edit
    @groups = Group.all
  end

  def create
  end

  def update
    #Get array from hash user_param
    user_params_as_array = user_params.values[1]
    #User_param with at least one group
    if user_params_as_array.count > 1
      if check_user_grups(get_groups_from_param(user_params), get_current_user_from_form(user_params))
        update_user_with_group(user_params[:group_ids], @user)
      else
        redirect_with_reject_of_update_of_user(@user)
      end
      #Empty user_param
    elsif user_params_as_array.count == 1
      update_user_with_group(user_params[:group_ids], @user)
    end
  end

  def destroy
  end

  def check_user_grups params,user
    delete_empty_char = params.pop
    user_params_as_array_to_int = params.map(&:to_i)
    if(user_params_as_array_to_int - user.group_ids).empty?
      return true
    else return false
    end
  end


def save_group_to_user param,user
  if user.update(:group_ids => param)
    true
  else
    false
end
end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
  def get_current_user_from_form param
    User.find(param.values[0].to_i)
  end

  def update_user_with_group param, user
    respond_to do |format|
      if save_group_to_user(param, user)
        format.html { redirect_to user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: user }
      end
    end
  end
  def redirect_with_reject_of_update_of_user user
    respond_to do |format|
      format.html { redirect_to user, notice: "User cannot be assign to this group"}
      format.json { render json: user.errors, status: :unprocessable_entity }
    end
  end
  def get_groups_from_param param
    user_params_as_array = param.values[1]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:current_user, :group_ids => [])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>User name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><b><%= group.name %></b></td>
        <td><%= group.users.map {|c| c.email}.join(', ') %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
  <%= @group.users.map {|c| c.email}.join(', ') %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/_header.html.erb
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>|
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
<% end %>
<%= link_to 'List of all users', users_path, :class => 'navbar-link' %> |
<%= link_to 'List of all groups', groups_path, :class => 'navbar-link' %> |
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<%= yield %>
</div>
</body>
</html>

app/views/static_pages/index.html.erb
<h1>WebSynergia App</h1>

<p> Example users from seed data <p>
<ul>	
<li>login: adam@test.pl, password: administrator1234</li>

<li>login: michal@test.pl', password: 'administrator1234</li> 

<li>login: tomasz@test.pl', password: administrator1234</li> 

<li>login: mikolaj@test.pl', password: 'administrator1234</li> 
<ul>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= collection_check_boxes(:user, :group_ids, @groups, :id, :name) %>
</div>
 <%= f.hidden_field :current_user, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1> User Edit </h1>
<h5>Your's groups [<b><%= current_user.groups.map {|c| c.name}.join(', ') %></b>]</h5>
<div class="well">
  <%= render 'form' %>
  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Group name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><b><%= user.email %></b></td>
        <td><%= user.groups.map {|c| c.name}.join(', ') %></td>
        <td><%= link_to 'Show', user %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/users/show.html.erb
<h1>User Name:    <%= @user.email %></h1>
<div class="well">
  <h5>Group name: <b><%= @user.groups.map {|c| c.name}.join(', ') %></b> </h5>
  <p id="notice"><%= notice %></p>
<% if user_signed_in? %>
    <p align="center"> <%= button_to "Edit", edit_user_path(@user),
    :class => "btn btn-default", :method => :get %></p>
<% end %>
</div>
<%= link_to 'Back', users_path %>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>